// Mocks generated by Mockito 5.4.4 from annotations
// in azkary/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:azkary/src/data/models/zekr_category_model.dart' as _i4;
import 'package:azkary/src/data/sources/audio_downloader.dart' as _i10;
import 'package:azkary/src/data/sources/audio_player_source.dart' as _i11;
import 'package:azkary/src/data/sources/audio_storage_source.dart' as _i13;
import 'package:azkary/src/data/sources/azkar_asset_source.dart' as _i5;
import 'package:azkary/src/data/sources/azkar_local_source.dart' as _i2;
import 'package:azkary/src/domain/entities/all_audios_download_progress.dart'
    as _i9;
import 'package:azkary/src/domain/entities/current_playback.dart' as _i7;
import 'package:azkary/src/domain/entities/download_progress.dart' as _i8;
import 'package:azkary/src/domain/entities/playback_state.dart' as _i12;
import 'package:azkary/src/domain/repositories/audio_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AzkarLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAzkarLocalSource extends _i1.Mock implements _i2.AzkarLocalSource {
  MockAzkarLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> hasCache() => (super.noSuchMethod(
        Invocation.method(
          #hasCache,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.ZekrCategoryModel>> readCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #readCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ZekrCategoryModel>>.value(
            <_i4.ZekrCategoryModel>[]),
      ) as _i3.Future<List<_i4.ZekrCategoryModel>>);

  @override
  _i3.Future<void> writeCategories(List<_i4.ZekrCategoryModel>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeCategories,
          [categories],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateZekrProgress(
    int? categoryId,
    int? zekrId,
    int? newCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateZekrProgress,
          [
            categoryId,
            zekrId,
            newCount,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetCategory(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #resetCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveLastResetTime(
    int? categoryId,
    String? isoTimestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLastResetTime,
          [
            categoryId,
            isoTimestamp,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getLastResetTime(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #getLastResetTime,
          [categoryId],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AzkarAssetSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAzkarAssetSource extends _i1.Mock implements _i5.AzkarAssetSource {
  MockAzkarAssetSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ZekrCategoryModel>> loadCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ZekrCategoryModel>>.value(
            <_i4.ZekrCategoryModel>[]),
      ) as _i3.Future<List<_i4.ZekrCategoryModel>>);
}

/// A class which mocks [AudioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRepository extends _i1.Mock implements _i6.AudioRepository {
  MockAudioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i7.CurrentPlayback?> get currentPlaybackStream =>
      (super.noSuchMethod(
        Invocation.getter(#currentPlaybackStream),
        returnValue: _i3.Stream<_i7.CurrentPlayback?>.empty(),
      ) as _i3.Stream<_i7.CurrentPlayback?>);

  @override
  _i3.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);

  @override
  _i3.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i3.Stream<Duration?>.empty(),
      ) as _i3.Stream<Duration?>);

  @override
  _i3.Future<void> downloadZekr(
    int? categoryId,
    int? zekrId, {
    _i8.DownloadProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadZekr,
          [
            categoryId,
            zekrId,
          ],
          {#onProgress: onProgress},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> downloadCategory(
    int? categoryId, {
    _i8.DownloadProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadCategory,
          [categoryId],
          {#onProgress: onProgress},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> downloadAllAudios(
          {_i9.AllAudiosDownloadProgressCallback? onProgress}) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAllAudios,
          [],
          {#onProgress: onProgress},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> cancelZekrDownload(
    int? categoryId,
    int? zekrId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelZekrDownload,
          [
            categoryId,
            zekrId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> cancelCategoryDownload(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelCategoryDownload,
          [categoryId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> cancelAllDownloads() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllDownloads,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> isZekrDownloaded(
    int? categoryId,
    int? zekrId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isZekrDownloaded,
          [
            categoryId,
            zekrId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isCategoryDownloaded(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #isCategoryDownloaded,
          [categoryId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> getZekrLocalPath(
    int? categoryId,
    int? zekrId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getZekrLocalPath,
          [
            categoryId,
            zekrId,
          ],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getCategoryLocalPath(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryLocalPath,
          [categoryId],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<Map<String, String>> readAllDownloadedPaths() =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllDownloadedPaths,
          [],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> playZekr(
    int? categoryId,
    int? zekrId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #playZekr,
          [
            categoryId,
            zekrId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playCategory(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #playCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAudioCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAudioCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AudioDownloader].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioDownloader extends _i1.Mock implements _i10.AudioDownloader {
  MockAudioDownloader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> download({
    required String? url,
    required String? destinationPath,
    _i8.DownloadProgressCallback? onProgress,
    _i10.DownloadCancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
          {
            #url: url,
            #destinationPath: destinationPath,
            #onProgress: onProgress,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AudioPlayerSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerSource extends _i1.Mock implements _i11.AudioPlayerSource {
  MockAudioPlayerSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i12.PlaybackState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i3.Stream<_i12.PlaybackState>.empty(),
      ) as _i3.Stream<_i12.PlaybackState>);

  @override
  _i3.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);

  @override
  _i3.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i3.Stream<Duration?>.empty(),
      ) as _i3.Stream<Duration?>);

  @override
  _i3.Future<void> loadFile(String? absolutePath) => (super.noSuchMethod(
        Invocation.method(
          #loadFile,
          [absolutePath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AudioStorageSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioStorageSource extends _i1.Mock
    implements _i13.AudioStorageSource {
  MockAudioStorageSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> has(String? key) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> put(
    String? key,
    String? storedPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            storedPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> readAll() => (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DownloadCancelToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadCancelToken extends _i1.Mock
    implements _i10.DownloadCancelToken {
  MockDownloadCancelToken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isCancelled => (super.noSuchMethod(
        Invocation.getter(#isCancelled),
        returnValue: false,
      ) as bool);

  @override
  void cancel([String? reason]) => super.noSuchMethod(
        Invocation.method(
          #cancel,
          [reason],
        ),
        returnValueForMissingStub: null,
      );
}
